repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-json
      - id: check-yaml
      # Add more general hooks as needed

  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.86.0
    hooks:
      - id: terraform_fmt
      - id: terraform_tflint
      # - id: terraform_checkov
        # args:
        #   - --args=--skip-check CKV_AWS_272,CKV_AWS_116,CKV_AWS_173,CKV_AWS_115,CKV_AWS_117,CKV_AWS_50,CKV2_AWS_61,CKV_AWS_18,CKV_AWS_145,CKV_AWS_144,CKV_AWS_56,CKV_AWS_55,CKV_AWS_21

  - repo: https://github.com/koalaman/shellcheck-precommit
    rev: v0.9.0
    hooks:
    - id: shellcheck
